### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by JokingAlpacaYT** [myStitch14/Gorilla-tag-Walk-sim-mod#11]
When you run in the new version you run super fast so is it supposed to happen or is it a bug?

**Comment by myStitch14** [comment]
Exactly how fast? you know what? just DM me a video on discord my user is "myStitch14"

**Comment by myStitch14** [comment]
Tell me if you sent the message tell me on this issue I am on do not disturb

**Comment by JokingAlpacaYT** [comment]
I'm sorry that it took so long here is the video about the speed! https://www.youtube.com/watch?v=VLmzNEoX1o4
