### ISSUE TITLE
I can't accept the TOS!

### ISSUE THREAD

**Issue by ST0PPY** [myStitch14/Gorilla-tag-Walk-sim-mod#12]
I can boot up and play the game, buy cosmetics etc. but I can't access the computer to change my colour code and join private codes + I can't load into online lobbies without accepting the TOS. That's where my problem comes to play, as far as I know there is now way to accept when it says 'HOLD ANY FACE BUTTON'. Please try to resolve this issue or (if there is a way to) inform me on how to accept the TOS. Thanks!

**Comment by myStitch14** [comment]
there is a mod menu that lets you accept the TOS on PC I am not sure witch one it is tho
