### ISSUE TITLE
it wont let me log into the game

### ISSUE THREAD

**Issue by calypsoooooo** [myStitch14/Gorilla-tag-Walk-sim-mod#13]
the computer is stuck on loggin in and i cant actually play the game

**Comment by myStitch14** [comment]
wdym "loggin"?

**Comment by calypsoooooo** [comment]
logging in

**Comment by myStitch14** [comment]
ohhhhhhh yea I had that glitch for while. soo I dont really know how to fix that... but if I remember I think your supposed to get the newest version of utilla

**Comment by saltsalter** [comment]
im having the same issue and i have the newest version of utilla idk what to do please help!! :(

**Comment by myStitch14** [comment]
hold on ima have to update the mod
