### ISSUE TITLE
Help w/ Design

### ISSUE THREAD

**Issue by LutraVibes** [myStitch14/Gorilla-tag-Walk-sim-mod#17]
Hello, Stitch! I would like to help you in the creation of the Walk Sim mod, to improve it and polish it. I have lots of experience in GUI design and coding. I have sent you a friend request on Discord. My username is "@lutravibes".

**Comment by NinjaGamer879** [comment]
Hello, if you do help in creating / polishing this mod please fix the computer it does not work

**Comment by LutraVibes** [comment]
> Hello, if you do help in creating / polishing this mod please fix the computer it does not work

You have to use the updated Clouds Revamp version
I had to update it for the computer to work

**Comment by NinjaGamer879** [comment]
Thanks

**Comment by XenonOrSomething** [comment]
he didnt make walksim, KyleTheScientist did, though he quit gtag modding
