### ISSUE TITLE
New update. Wont work.

### ISSUE THREAD

**Issue by getthepickles** [myStitch14/Gorilla-tag-Walk-sim-mod#6]
So the new update came and when I try to go on gorilla tag the menu won't work.

**Comment by getthepickles** [comment]
No.

**Comment by penguuus** [comment]
damn

**Comment by penguuus** [comment]
> So the new update came and when I try to go on gorilla tag the menu won't work.

a wise man once said:
A screen once filled with options galore,
Now silent, the choices work no more.
Where laughter and joy once freely spun,
The silence weighs heavy, the fun undone.

In pixels and bytes, our hopes were cast,
For games that launch and memories that last.
But with every update, there's risk we take,
That a glitch might appear, and our hearts it breaks.

So here we stand, in a virtual freeze,
A moment of silence, a digital plea.
May the coders hear our united cry,
And fix the menu, so our spirits can fly.

For now, we wait in this quiet spell,
A tale of updates not going so well.
But hope springs eternal in the gamer's heart,
For a patch, a fix, a brand new start.
